m4_define(`TOOLCHAIN',macosx)m4_dnl
m4_define(`PPA_CLANG',-10)m4_dnl
m4_define(`MACOSX_SDK_VERSION',11.0)m4_dnl
m4_define(`MACOSX_TARGET_ARCH',x86_64)m4_dnl
m4_define(`MACOSX_TARGET_VERSION',20)m4_dnl
m4_define(`MACOSX_DEPLOYMENT_TARGET',10.9)m4_dnl
m4_define(`MACOSX_ARCHITECTURES',`x86_64')m4_dnl
m4_define(`MACOSX_PORTS_ARCH_ARG',`')m4_dnl
m4_include(`macosx.m4')m4_dnl
